### ISSUE TITLE
Consider using builtin importlib.metadata

### ISSUE THREAD

**Issue by EvaSDK** [anthonyharrison/sbom4python#17]
Using `pip show` to collect package metadata only returns a select few metadata of a package.
Using `importlib.metadata` would allow accessing to all of them, such as Download-URL, Project-URL, and Maintainer. See https://packaging.python.org/en/latest/specifications/core-metadata/.
This should make the code slightly faster and more reliable.

**Comment by anthonyharrison** [comment]
Thanks for the suggestion.
