### ISSUE TITLE
Homebrew version of sbom4python  is not up to date

### ISSUE THREAD

**Issue by vargenau** [anthonyharrison/sbom4python#21]
As of today current version of sbom4python is v0.11.1 

Homebrew gives version 0.10.3

```
brew update
==> Updating Homebrew...
Already up-to-date.
brew upgrade
sbom4python --version
0.10.3
```

**Comment by anthonyharrison** [comment]
@vargenau I didn't know sbom4python was on homebrew (I couldn't find it when I searched for it [here](https://formulae.brew.sh/).

I have no idea how homebrew updates its packages. Any insights?

**Comment by vargenau** [comment]
@anthonyharrison 
I am sorry, but in fact I did not install sbom4python with Homebrew but with a `pip install`.
What confused me is that sbom4python is installed inside the homebrew directory:
```
which sbom4python
/opt/homebrew/bin/sbom4python
```
This is due to the fact that python and pip are managed by Homebrew.
