### ISSUE TITLE
docs: add examples to the repo

### ISSUE THREAD

**Issue by jkowalleck** [anthonyharrison/sbom4python#26]
The sbom4python tool can generate output in CycloneDX and SPDX - each in different formats. And it can generate dependency graphs.

It would be great to see examples for these output results.

My idea: have a folder "examples" in this very repository, that includes an example python project and a file for each possible output result of sbom4python. I think there is no need to have reproducible examples - but if intended, then running in a docker/container could be a go-to solution.

**Comment by anthonyharrison** [comment]
Thanks @jkowalleck. Will add it to my backlog.
