### ISSUE TITLE
Dependency Tree vs Dependency Graph

### ISSUE THREAD

**Issue by dmholtz** [anthonyharrison/sbom4python#3]
As far as I have understood the implementation of the `scanner.py` module, it builds a dependency tree. In the end, every package A has at most one unique parent, which requires A.

IMO this assumption is not correct, because multiple packages may require A as a first-level dependency:

Example (obtained using `pip show XY`):

- `flask` requires: click, itsdangerous, Jinja2, Werkzeug
- `jinja2`requires: MarkupSafe
- `Werkzeug` requires: MarkupSafe

Here, `MarkupSafe` has multiple parents and thus one relationship is missed.

sbom4python should rather build a dependency graph than a dependency in order to ensure not to miss any relationships in the SBOMs.

**Comment by anthonyharrison** [comment]
@dmholtz Thanks for the feedback (and support!)

When I run sbom4python on flask, I get the following relationships

Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-1-Flask
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-2-click
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-3-itsdangerous
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-4-jinja2
Relationship: SPDXRef-Package-4-jinja2 CONTAINS SPDXRef-Package-5-markupsafe
Relationship: SPDXRef-Package-4-jinja2 CONTAINS SPDXRef-Package-6-werkzeug
Relationship: SPDXRef-Package-6-werkzeug CONTAINS SPDXRef-Package-5-markupsafe

which shows Markupsafe as being the parent for both jinja and Werkzeug

**Comment by dmholtz** [comment]
@anthonyharrison Thank you very much for your detailed response!

First of all, please apologize the following statement, which was wrong because I did not read the output correctly:
> Here, `MarkupSafe` has multiple parents and thus one relationship is missed.

By iteratively calling `pip show XY` I determined the following dependency graph, which differs from your graph (and the output)
![grafik](https://user-images.githubusercontent.com/56723830/212552063-9c960336-cf98-4d6e-9751-9e7c4ec5b74e.png)

Please note, that every the arrow represents a `DEPENDS-ON` relationships.

The following aspects remain unclear to me:
1. What is the difference between uppercase Flask and lowercase flask?
2. What are the semantics of the `DESCRIBES` relationship here? If I am reading the [documentation](https://spdx.github.io/spdx-spec/v2-draft/relationships-between-SPDX-elements/) correctly, it describes logical relations between a SPDX document and a SPDX ref (e.g. any package declared within a document). Thus, I believe it should not be used describe build dependencies between packages.
3. The relationship `Relationship: SPDXRef-Package-4-jinja2 CONTAINS SPDXRef-Package-6-werkzeug` should not exist IMO.

I'm afraid that I cannot precisely tell the reason for the last issue. This is merely due to the fact that I do not understand how the dependency graph is represented in your data structures.

**Comment by anthonyharrison** [comment]
@dmholtz I will investigate as your analysis is identifying some issues with some of the inter-dependencies whcih I haven't seen before.

Having looked at your comment, it looks like the Werkzeug relationship with flask is being missed (or lost!) and Jinja is gaining a relationship with Werkzeug. I also am now wondering if the DESCRIBES relationship should only refer to root module  e.g.
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-1-Flask

BTW I convert all names to lowercase which accounts for the Flask becoming flask.

**Comment by anthonyharrison** [comment]
@dmholtz I have found the problem. It is related the the difference between Flask and flask. Resolving the issue results in the following tree structure (which now looks correct). 

![image](https://user-images.githubusercontent.com/8421867/212556207-7c6e19ef-8fc8-4266-ba1e-4755cc7e420d.png)

Will push through the commits and create a new release.

**Comment by anthonyharrison** [comment]
Corrected in v0.7.0

**Comment by dmholtz** [comment]
Thank you very much! Looks good to me now.
