### ISSUE TITLE
BUGFIX:  various bugs when a line of `pip show module` does not contain an ":" delimited entry.

### ISSUE THREAD

**Issue by You-ne** [anthonyharrison/sbom4python#8]
## Description

Whenever the result of `pip show module`, that is stored in `out`, then parsed line by line (which are stored in the array `entry`);
contains a line that: 
1. either contains a line wich can't be split with ":" as a delimiter because it doesn't contain it.
2. either a line that contains the ":" character, but where it is not used to delimit a relevant field for `sbom4python`.

A bug arises.

In case 1, the execution stops with a "__list index out of range__" error.
In case 2, the resulting SBOM _contains meaningless fields_.

__CASE 1__ error trace:
```python
Traceback (most recent call last):
  File "/home/user/project/.venv/bin/sbom4python", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/project/.venv/lib/python3.11/site-packages/sbom4python/cli.py", line 134, in main
    sbom_scan.process_python_module(module_name)
  File "/home/user/project/.venv/lib/python3.11/site-packages/sbom4python/scanner.py", line 213, in process_python_module
    self.analyze(self.get("Name"), self.get("Requires"))
  File "/home/user/project/.venv/lib/python3.11/site-packages/sbom4python/scanner.py", line 207, in analyze
    if self.process_module(r, parent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/project/.venv/lib/python3.11/site-packages/sbom4python/scanner.py", line 78, in process_module
    line.split(f"{entry[0]}:", 1)[1].strip().rstrip("\n")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

It seems that some modules return a uncommonly formatted value when `pip show module`, for example `kiwisolver`.

## Reproduction

To reproduce this error: 
after creating a fresh `.venv` (`python 3.11.2` for me), run :

```bash
pip install sbom4python kiwisolver
sbom4python -d -m kiwisolver
```

**Comment by anthonyharrison** [comment]
@You-ne Thanks foir the report which I just found this after upissuing SBOM4PYTHON! I have confirmed that the bug still exists in the updated version as it would appear that the kiwisolver License information is not well aligned with the standard Python packaging structure. I will have a look at your proposed pull request and see if it needs any further changes.
